packages:
    - "examples/**/*"
    - "packages/**/*"
    - "!**/.next/**"
    - "!**/dist/**"

catalog:
    viem: 2.21.49
    zod: 3.23.8
    "@solana/web3.js": 1.95.8
    ai: 4.0.3
    "@langchain/core": 0.3.6
    "@lit-protocol/lit-node-client": "7.0.2"
    "@lit-protocol/types": "7.0.2"
    "@lit-protocol/lit-auth-client": "7.0.2"
    "@lit-protocol/auth-helpers": "7.0.2"
    "@lit-protocol/constants": "7.0.2"
    "@lit-protocol/contracts-sdk": "7.0.2"
    "@lit-protocol/misc": "7.0.2"
    "@lit-protocol/wrapped-keys": "7.0.2"
